src/objects/Actor__c.object
<CustomObject>
    <fields>
        <fullName>Biography__c</fullName>
        <label>Biography</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Birthday__c</fullName>
        <label>Birthday</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deathday__c</fullName>
        <label>Deathday</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Known_as__c</fullName>
        <label>Known as</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Place_of_birth__c</fullName>
        <label>Place of birth</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Profile_path__c</fullName>
        <label>Profile path</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Actor</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Actors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MPSiteActorWrapper.cls
public with sharing class MPSiteActorWrapper {

    public Date birthday;
    public Date deathday;
    public String id;
    public String name;
    public String also_known_as;
    public String biography;
    public String place_of_birth;
    public String profile_path;
    public String source;
    public String character;

    public MPSiteActorWrapper(MPActorWrapper actorWrapper) {
        this.source = 'external';
        this.biography = actorWrapper.biography;
        this.deathday = actorWrapper.deathday;
        this.id = actorWrapper.id;
        this.name = actorWrapper.name;
        this.also_known_as = knowAsString(actorWrapper.also_known_as);
        this.birthday = actorWrapper.birthday;
        this.place_of_birth = actorWrapper.place_of_birth;
        this.profile_path = actorWrapper.profile_path;
    }

    public MPSiteActorWrapper(Actor__c actor) {
        this.source = 'internal';
        this.biography = actor.Biography__c;
        this.deathday = actor.Deathday__c;
        this.id = actor.Id;
        this.name = actor.Name;
        this.also_known_as = actor.Known_as__c;
        this.birthday = actor.Birthday__c;
        this.place_of_birth = actor.Place_of_birth__c;
        this.profile_path = actor.Profile_path__c;
    }

    public MPSiteActorWrapper(MPActorSearchWrapper.Actors actor){
        this.source = 'external';
        this.name = actor.name;
        this.id = actor.id;
        this.profile_path = actor.profile_path;
    }

    public MPSiteActorWrapper(MPCastAndCrewWrapper.Cast_Z actor) {
        this.source = 'external';
        this.name = actor.name;
        this.id = actor.id;
        this.profile_path = actor.profile_path;
        this.character = actor.character;
    }

    public String knowAsString(List<String> stringList){
        String knowAs = '';
        for (String s : stringList){
            knowAs += s + ', ';
        }
        return knowAs.removeEnd(', ');
    }
}