src/objects/Favorited_And_Blacklisted__c.object
<CustomObject>
    <fields>
        <fullName>MovieId__c</fullName>
        <label>MovieId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Favorite</fullName>
                </value>
                <value>
                    <fullName>Black List</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Favorited_And_Blacklisteds</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Favorited And Blacklisted</label>
    <nameField>
        <displayFormat>F-{00000}</displayFormat>
        <label>Favorited And Blacklisted Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Favorited And Blacklisteds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Movie__c.object
<CustomObject>
    <fields>
        <fullName>Budget__c</fullName>
        <label>Budget</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Genres__c</fullName>
        <label>Genres</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Action</fullName>
                </value>
                <value>
                    <fullName>Adventure</fullName>
                </value>
                <value>
                    <fullName>Animation</fullName>
                </value>
                <value>
                    <fullName>Comedy</fullName>
                </value>
                <value>
                    <fullName>Crime</fullName>
                </value>
                <value>
                    <fullName>Documentary</fullName>
                </value>
                <value>
                    <fullName>Family</fullName>
                </value>
                <value>
                    <fullName>Fantasy</fullName>
                </value>
                <value>
                    <fullName>History</fullName>
                </value>
                <value>
                    <fullName>Horror</fullName>
                </value>
                <value>
                    <fullName>Music</fullName>
                </value>
                <value>
                    <fullName>Mystery</fullName>
                </value>
                <value>
                    <fullName>Romance</fullName>
                </value>
                <value>
                    <fullName>Science Fiction</fullName>
                </value>
                <value>
                    <fullName>TV Movie</fullName>
                </value>
                <value>
                    <fullName>Thriller</fullName>
                </value>
                <value>
                    <fullName>War</fullName>
                </value>
                <value>
                    <fullName>Western</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Homepage__c</fullName>
        <label>Homepage</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Overview__c</fullName>
        <label>Overview</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Poster_path__c</fullName>
        <label>Poster path</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Production_companies__c</fullName>
        <label>Production companies</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Release_date__c</fullName>
        <label>Release date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Runtime__c</fullName>
        <description>Time in minutes</description>
        <label>Runtime</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Movie</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Review__c.object
<CustomObject>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Id__c</fullName>
        <label>Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rating__c</fullName>
        <label>Rating</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Movie</fullName>
                </value>
                <value>
                    <fullName>Actor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Review</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MPSiteController.cls
public with sharing class MPSiteController {

//public static String movieId = '458156';
    @AuraEnabled
    public static MPMovieWrapper getMovieDetail(String movieId) {
        MPMovieWrapper movie = MPRestController.getMovieById(movieId);
        movie.source = 'external';
        List<Favorited_And_Blacklisted__c> oldList = [Select MovieId__c, Type__c FROM Favorited_And_Blacklisted__c WHERE User__c = :UserInfo.getUserId()];
        for(Favorited_And_Blacklisted__c fb : oldList) {
            if (movie.id == fb.MovieId__c) {
                movie.FBtype = fb.Type__c;
            }
        }
        return movie;
    }
    @AuraEnabled
    public static List<MPCastAndCrewWrapper.Cast_Z> getMovieCast(String movieId) {
        List<MPCastAndCrewWrapper.Cast_Z> castList = MPRestController.getMovieCast(movieId);
        return castList;
    }
    @AuraEnabled
    public static List<MPMovieImagesWrapper.Backdrops> getMovieImages(String movieId) {
        List<MPMovieImagesWrapper.Backdrops> images = MPRestController.getMovieImages(movieId);
        return images;
    }
    @AuraEnabled
    public static List<MPMovieVideosWrapper.Trailer> getMovieTrailers(String movieId) {
        List<MPMovieVideosWrapper.Trailer> trailers = MPRestController.getMovieVideos(movieId);
        return trailers;
    }

//public static String actorId = '3894';
    @AuraEnabled
    public static MPActorWrapper getActorDetail(String actorId) {
        MPActorWrapper actor = MPRestController.getActorById(actorId);
        return actor;
    }
    @AuraEnabled
    public static List<MPActorFilmographyWrapper.Cast_Z> getActorFilmography(String actorId) {
        List<MPActorFilmographyWrapper.Cast_Z> filmography = MPRestController.getActorFilmography(actorId);
        return filmography;
    }
    @AuraEnabled
    public static List<MPActorImagesWrapper.Images> getActorImages(String actorId) {
        List<MPActorImagesWrapper.Images> images = MPRestController.getActorImages(actorId);
        return images;
    }

//rest
    @AuraEnabled
    public static List<MPPopularMoviesWrapper.PopularMovies> getPopularMovies() {
        List<MPPopularMoviesWrapper.PopularMovies> popularMovies = MPRestController.getPopularFilms();
        for(MPPopularMoviesWrapper.PopularMovies p : popularMovies){
            p.source = 'external';
        }
        return popularMovies;
    }
    public static void getGenres(){
        List<MPGenreWrapper.Genres> genres = MPRestController.getGenres();
        for(MPGenreWrapper.Genres g : genres){
            System.debug(g);
        }
    }

//public static String query = 'nicholson';
    @AuraEnabled
    public static MPMovieSearchWrapper searchMovies(String query, Integer page){
        MPMovieSearchWrapper movies = MPRestController.searchMovies(query, page);
        for(MPMovieSearchWrapper.Movies w : movies.results){
            w.source = 'external';
        }
        if(page == 1) {
            String stringQuery = 'SELECT Budget__c, Genres__c, Homepage__c, Id, Name, Overview__c, Poster_path__c, Production_companies__c, Release_date__c, Runtime__c FROM Movie__c WHERE Name LIKE \'%' + query + '%\'';
            List<Movie__c> internalMovies = Database.query(stringQuery);
            if(!internalMovies.isEmpty()){
                for(Movie__c m : internalMovies){
                    movies.results.add(new MPMovieSearchWrapper.Movies(m));
                }
            }
        }
        return movies;
    }

    @AuraEnabled
    public static MPActorSearchWrapper searchActors(String query, Integer page){
        MPActorSearchWrapper actors = MPRestController.searchActors(query, page);
        return actors;
    }

    @AuraEnabled
    public static List<Review__c> getReviews(String objectId, String context){
        List<Review__c> reviews =[SELECT Id, Name, Comment__c, Rating__c, LastModifiedDate, CreatedDate,CreatedBy.Name ,CreatedBy.SmallPhotoUrl FROM Review__c WHERE Id__c=:objectId AND Type__c LIKE :context];
        return reviews;
    }

    @AuraEnabled
    public static MPMovieWrapper addToBFList(String movieId, String FBType){
        String oldType = '';
        MPMovieWrapper movie = MPRestController.getMovieById(movieId);
        List<Favorited_And_Blacklisted__c> oldList = [Select Id,Type__c FROM Favorited_And_Blacklisted__c WHERE User__c = :UserInfo.getUserId() AND MovieId__c = :movieId];
        if(!oldList.isEmpty()) {
            oldType = oldList.get(0).Type__c;
            delete oldList;
        }
        if(oldType != FBType || oldList.isEmpty()) {
            Favorited_And_Blacklisted__c newObject = new Favorited_And_Blacklisted__c();
            newObject.Type__c = FBType;
            newObject.User__c = UserInfo.getUserId();
            newObject.MovieId__c = movieId;
            insert newObject;
            movie.FBtype = FBType;
        }
    return movie;
    }

    @AuraEnabled
    public static void addMovie(String movie){
        Movie__c newMovie = (Movie__c) JSON.deserialize(movie, Movie__c.class);
        List<Movie__c> oldMovies = [SELECT Name, Budget__c, Release_date__c FROM Movie__c WHERE Name LIKE :newMovie.Name];
        if(!oldMovies.isEmpty()){
            throw new AuraHandledException('The Movie with title ' + newMovie.Name +' already exists');
        } else {
            insert newMovie;
        }
    }

    @AuraEnabled
    public static BFlist getBF(){
        List<Favorited_And_Blacklisted__c> bfList = [SELECT MovieId__c, Type__c, User__c FROM Favorited_And_Blacklisted__c WHERE User__c = :UserInfo.getUserId()];
        if(bfList.isEmpty()) return null;
        BFlist bf = new BFlist();
        List<MPMovieWrapper> favorite = new List<MPMovieWrapper>();
        List<MPMovieWrapper> blacklist = new List<MPMovieWrapper>();
        for(Favorited_And_Blacklisted__c item : bfList){
            MPMovieWrapper movie = MPRestController.getMovieById(item.MovieId__c);
            movie.FBtype = item.Type__c;
            if(item.Type__c == 'Favorite') favorite.add(movie);
            if(item.Type__c == 'Black List') blacklist.add(movie);
        }
        bf.blacklist = blacklist;
        bf.favorite = favorite;
        System.debug(bf.favorite);
        System.debug(bf.blacklist);
        return bf;
    }

    public class BFlist {
        @AuraEnabled public List<MPMovieWrapper> favorite;
        @AuraEnabled public List<MPMovieWrapper> blacklist;
    }
}