src/objects/Movie__c.object
<CustomObject>
    <fields>
        <fullName>Budget__c</fullName>
        <label>Budget</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Genres__c</fullName>
        <label>Genres</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Action</fullName>
                </value>
                <value>
                    <fullName>Adventure</fullName>
                </value>
                <value>
                    <fullName>Animation</fullName>
                </value>
                <value>
                    <fullName>Comedy</fullName>
                </value>
                <value>
                    <fullName>Crime</fullName>
                </value>
                <value>
                    <fullName>Documentary</fullName>
                </value>
                <value>
                    <fullName>Family</fullName>
                </value>
                <value>
                    <fullName>Fantasy</fullName>
                </value>
                <value>
                    <fullName>History</fullName>
                </value>
                <value>
                    <fullName>Horror</fullName>
                </value>
                <value>
                    <fullName>Music</fullName>
                </value>
                <value>
                    <fullName>Mystery</fullName>
                </value>
                <value>
                    <fullName>Romance</fullName>
                </value>
                <value>
                    <fullName>Science Fiction</fullName>
                </value>
                <value>
                    <fullName>TV Movie</fullName>
                </value>
                <value>
                    <fullName>Thriller</fullName>
                </value>
                <value>
                    <fullName>War</fullName>
                </value>
                <value>
                    <fullName>Western</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Homepage__c</fullName>
        <label>Homepage</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Overview__c</fullName>
        <label>Overview</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Poster_path__c</fullName>
        <label>Poster path</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Production_companies__c</fullName>
        <label>Production companies</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Release_date__c</fullName>
        <label>Release date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Runtime__c</fullName>
        <description>Time in minutes</description>
        <label>Runtime</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Movie</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MPSiteMovieWrapper.cls
public with sharing class MPSiteMovieWrapper {

    public String budget;
    public String genres;
    public String homepage;
    public String id;
    public String overview;
    public String poster_path;
    public String production_companies;
    public Date release_date;
    public Decimal runtime;
    public String title;
    public String source;
    public String character;

    public MPSiteMovieWrapper(MPMovieWrapper movieWrapper){
        this.source = 'external';
        this.budget = movieWrapper.budget;
        this.genres = genresString(movieWrapper.genres);
        this.homepage = movieWrapper.homepage;
        this.id = movieWrapper.id;
        this.overview = movieWrapper.overview;
        this.poster_path = movieWrapper.poster_path;
        this.production_companies = companiesString(movieWrapper.production_companies);
        this.release_date = movieWrapper.release_date;
        this.runtime = movieWrapper.runtime;
        this.title = movieWrapper.title;
    }

    public MPSiteMovieWrapper(Movie__c movie){
        this.source = 'internal';
        this.budget = movie.Budget__c;
        this.genres = movie.Genres__c;
        this.homepage = movie.Homepage__c;
        this.id = movie.Id;
        this.overview = movie.Overview__c;
        this.poster_path = movie.Poster_path__c;
        this.production_companies = movie.Production_companies__c;
        this.release_date = movie.Release_date__c;
        this.runtime = movie.Runtime__c;
        this.title = movie.Name;
    }

    public MPSiteMovieWrapper(MPMovieSearchWrapper.Movies movie){
        this.source = 'external';
        this.id = movie.id;
        this.title = movie.title;
        this.poster_path = movie.poster_path;
    }

    public MPSiteMovieWrapper(MPActorFilmographyWrapper.Cast_Z movie){
        this.source = 'external';
        this.id = movie.id;
        this.title = movie.title;
        this.poster_path = movie.poster_path;
        this.character = movie.character;
    }

    public String companiesString(List<MPMovieWrapper.Production_companies> companiesList){
        String companies = '';
        for(MPMovieWrapper.Production_companies p : companiesList){
            companies += p.name + ', ';
        }
        return companies.removeEnd(', ');
    }

    public String genresString(List<MPMovieWrapper.Genres> genresList){
        String genresString = '';
        for ( MPMovieWrapper.Genres g : genresList){
            genresString += g.name + ', ';
        }
        return genresString.removeEnd(', ');
    }
}